DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;
CREATE TABLE pet(
    id INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (50) UNIQUE NOT NULL,
    favorite_color VARCHAR (50) NOT NULL,
    pet_type VARCHAR (50) NOT NULL

);